// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getmean_cpp
NumericVector getmean_cpp(const NumericVector& X_vec, const List& beta, int n, int p, int d, int rank);
RcppExport SEXP _TensorMCMC_getmean_cpp(SEXP X_vecSEXP, SEXP betaSEXP, SEXP nSEXP, SEXP pSEXP, SEXP dSEXP, SEXP rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type X_vec(X_vecSEXP);
    Rcpp::traits::input_parameter< const List& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    rcpp_result_gen = Rcpp::wrap(getmean_cpp(X_vec, beta, n, p, d, rank));
    return rcpp_result_gen;
END_RCPP
}
// update_beta_cpp
List update_beta_cpp(List beta, int p, int d, int rank, double sigma);
RcppExport SEXP _TensorMCMC_update_beta_cpp(SEXP betaSEXP, SEXP pSEXP, SEXP dSEXP, SEXP rankSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(update_beta_cpp(beta, p, d, rank, sigma));
    return rcpp_result_gen;
END_RCPP
}
// predict_tensor_cpp
NumericVector predict_tensor_cpp(const NumericVector& X_vec, const List& beta, const NumericVector& gam, int n, int p, int d, int rank);
RcppExport SEXP _TensorMCMC_predict_tensor_cpp(SEXP X_vecSEXP, SEXP betaSEXP, SEXP gamSEXP, SEXP nSEXP, SEXP pSEXP, SEXP dSEXP, SEXP rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type X_vec(X_vecSEXP);
    Rcpp::traits::input_parameter< const List& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type gam(gamSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type rank(rankSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_tensor_cpp(X_vec, beta, gam, n, p, d, rank));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TensorMCMC_getmean_cpp", (DL_FUNC) &_TensorMCMC_getmean_cpp, 6},
    {"_TensorMCMC_update_beta_cpp", (DL_FUNC) &_TensorMCMC_update_beta_cpp, 5},
    {"_TensorMCMC_predict_tensor_cpp", (DL_FUNC) &_TensorMCMC_predict_tensor_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_TensorMCMC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}

