# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getmean_cpp <- function(X_vec, beta, n, p, d, rank) {
    .Call(`_TensorMCMC_getmean_cpp`, X_vec, beta, n, p, d, rank)
}

update_beta_cpp <- function(beta, p, d, rank, sigma) {
    .Call(`_TensorMCMC_update_beta_cpp`, beta, p, d, rank, sigma)
}

predict_tensor_cpp <- function(X_vec, beta, gam, n, p, d, rank) {
    .Call(`_TensorMCMC_predict_tensor_cpp`, X_vec, beta, gam, n, p, d, rank)
}
